kind = "mobile"
previewPath = "/mobile/"
title = "Jatek Livreur"
version = "1.0.0"
id = "artifacts/jatek-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/mobile/" ]
localPort = 25896

[services.development]
run = "pnpm --filter @workspace/jatek-driver run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/jatek-driver", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/jatek-driver", "run", "serve" ]

[services.env]
PORT = "25896"
BASE_PATH = "/mobile/"
